  - name: Install required packages
    become: true
    apt:
      name:
        - git
      state: present
  
  - name: Upload SSH key for Github
    copy:
      src: "{{ github_key_local_location }}"
      dest: "{{ github_key_remote_location }}"
      mode: "0600"
      force: yes

  - name: Cleanup repo
    file:
      state: absent
      path: "{{ project_remote_location }}"

  - name: Clone repository
    git:
      repo: "{{ project_repo }}"
      dest: "{{ project_remote_location }}"
      key_file: "{{ github_key_remote_location }}"
      accept_newhostkey: yes
      clone: yes

  - name: Copy .env to remote
    template:
      src: "templates/.env.j2"
      dest: "{{ project_remote_location }}/.env"
      mode: "0600"
      force: yes
