  - name: Tear down existing services
    community.docker.docker_compose:
      project_src: "{{ project_remote_location }}"
      state: absent

  - name: Create and start services
    community.docker.docker_compose:
      project_src: "{{ project_remote_location }}"
